import { UpcomingExpedition } from "@/types/types";

export const dummyUpcomingExpeditions: UpcomingExpedition[] = [
  {
    id: "exp-001",
    title: "Mount Kenya Summit Expedition",
    destination: "Mount Kenya",
    image: "/images/expeditions/mount-kenya.jpg",
    departureDate: "2026-07-12",
    returnDate: "2026-07-15",
    duration: "4 Days",
    difficulty: "Advanced",
    price: 24500,
    slotsLeft: 7,
    capacity: 15,
    meetingPoint: "Nairobi CBD",
    guide: "David Mwangi",
    status: "Open",
    description:
      "Reach Point Lenana through the scenic Sirimon route while camping beneath the stars.",
  },

  {
    id: "exp-002",
    title: "Ngong Hills Sunrise Adventure",
    destination: "Ngong Hills",
    image: "/images/expeditions/ngong-hills.jpg",
    departureDate: "2026-07-19",
    returnDate: "2026-07-19",
    duration: "1 Day",
    difficulty: "Beginner",
    price: 2500,
    slotsLeft: 18,
    capacity: 25,
    meetingPoint: "Kencom, Nairobi",
    guide: "Faith Wanjiru",
    status: "Open",
    description:
      "Catch an unforgettable sunrise over Nairobi while exploring the famous Ngong Hills.",
  },

  {
    id: "exp-003",
    title: "Hell's Gate & Gorge Trek",
    destination: "Naivasha",
    image: "/images/expeditions/hells-gate.jpg",
    departureDate: "2026-07-26",
    returnDate: "2026-07-26",
    duration: "1 Day",
    difficulty: "Intermediate",
    price: 4800,
    slotsLeft: 10,
    capacity: 20,
    meetingPoint: "Nairobi CBD",
    guide: "Kevin Kiptoo",
    status: "Open",
    description:
      "Walk through dramatic gorges, geothermal formations and spot wildlife on foot.",
  },

  {
    id: "exp-004",
    title: "Aberdare Elephant Hill Challenge",
    destination: "Aberdare Ranges",
    image: "/images/expeditions/elephant-hill.jpg",
    departureDate: "2026-08-02",
    returnDate: "2026-08-02",
    duration: "1 Day",
    difficulty: "Advanced",
    price: 5500,
    slotsLeft: 5,
    capacity: 15,
    meetingPoint: "Garden City Mall",
    guide: "Samuel Kariuki",
    status: "Almost Full",
    description:
      "A demanding but rewarding climb through bamboo forests to stunning viewpoints.",
  },

  {
    id: "exp-005",
    title: "Mount Longonot Crater Hike",
    destination: "Naivasha",
    image: "/images/expeditions/longonot.jpg",
    departureDate: "2026-08-09",
    returnDate: "2026-08-09",
    duration: "1 Day",
    difficulty: "Intermediate",
    price: 4200,
    slotsLeft: 13,
    capacity: 20,
    meetingPoint: "Nairobi CBD",
    guide: "Brian Mutiso",
    status: "Open",
    description:
      "Climb the extinct volcano and walk around the breathtaking crater rim.",
  },

  {
    id: "exp-006",
    title: "Karura Forest Wellness Walk",
    destination: "Karura Forest",
    image: "/images/expeditions/karura.jpg",
    departureDate: "2026-08-16",
    returnDate: "2026-08-16",
    duration: "Half Day",
    difficulty: "Easy",
    price: 1500,
    slotsLeft: 24,
    capacity: 30,
    meetingPoint: "Karura Main Gate",
    guide: "Mercy Njeri",
    status: "Open",
    description:
      "A relaxed nature walk perfect for beginners, families and photography lovers.",
  },

  {
    id: "exp-007",
    title: "Menengai Crater Exploration",
    destination: "Nakuru",
    image: "/images/expeditions/menengai.jpg",
    departureDate: "2026-08-23",
    returnDate: "2026-08-23",
    duration: "1 Day",
    difficulty: "Beginner",
    price: 3500,
    slotsLeft: 16,
    capacity: 25,
    meetingPoint: "Nairobi CBD",
    guide: "John Ochieng",
    status: "Open",
    description:
      "Explore one of Africa's largest volcanic calderas with sweeping Rift Valley views.",
  },

  {
    id: "exp-008",
    title: "Castle Forest Waterfalls Expedition",
    destination: "Kirinyaga",
    image: "/images/expeditions/castle-forest.jpg",
    departureDate: "2026-08-30",
    returnDate: "2026-08-31",
    duration: "2 Days",
    difficulty: "Intermediate",
    price: 12800,
    slotsLeft: 6,
    capacity: 12,
    meetingPoint: "Nairobi CBD",
    guide: "James Kamau",
    status: "Limited",
    description:
      "Discover hidden waterfalls, lush indigenous forests and scenic camping spots.",
  },
];
