import { FeaturedHike } from "@/types/types";

export const dummyFeaturedHikes: FeaturedHike[] = [
  {
    id: "hike-001",
    title: "Mount Kenya - Sirimon Route",
    description:
      "Experience Kenya's highest mountain through the scenic Sirimon Route, featuring alpine landscapes, dramatic ridges, and unforgettable sunrise views.",
    image: "/explore/mt-kenya.png",
    difficulty: "Intermediate",
    duration: "4 Days",
    price: 18500,
    rating: 4.9,
    location: "Laikipia County",
    distanceFromNairobi: "Approx. 4.5 hrs drive",
  },
  {
    id: "hike-002",
    title: "Ngong Hills Sunrise Hike",
    description:
      "A refreshing half-day adventure through the iconic rolling hills with breathtaking sunrise views overlooking Nairobi.",
    image: "/explore/ngong-hills-2.png",
    difficulty: "Beginner",
    duration: "1 Day",
    price: 2500,
    rating: 4.8,
    location: "Kajiado County",
    distanceFromNairobi: "45 mins drive",
  },
  {
    id: "hike-003",
    title: "Aberdare Elephant Hill",
    description:
      "Challenge yourself on one of Kenya's most rewarding hikes through bamboo forests, waterfalls, and panoramic mountain scenery.",
    image: "/explore/elep-hill.jpg",
    difficulty: "Advanced",
    duration: "1 Day",
    price: 4500,
    rating: 4.8,
    location: "Nyeri County",
    distanceFromNairobi: "4 hrs drive",
  },
  {
    id: "hike-004",
    title: "Mount Longonot Crater Trail",
    description:
      "Climb the famous volcanic mountain and walk around the crater rim while enjoying spectacular Rift Valley views.",
    image: "/explore/longonot.png",
    difficulty: "Intermediate",
    duration: "1 Day",
    price: 3800,
    rating: 4.7,
    location: "Naivasha",
    distanceFromNairobi: "2 hrs drive",
  },
  {
    id: "hike-005",
    title: "Karura Forest Nature Walk",
    description:
      "Enjoy a peaceful forest escape with waterfalls, caves, cycling trails, and abundant birdlife right in Nairobi.",
    image: "/explore/karura.png",
    difficulty: "Easy",
    duration: "Half Day",
    price: 1200,
    rating: 4.9,
    location: "Nairobi",
    distanceFromNairobi: "20 mins drive",
  },
  {
    id: "hike-006",
    title: "Hell's Gate Gorge Adventure",
    description:
      "Walk among towering cliffs, geothermal features, and wildlife in one of Kenya's most unique national parks.",
    image: "/explore/hell.png",
    difficulty: "Intermediate",
    duration: "1 Day",
    price: 4200,
    rating: 4.8,
    location: "Naivasha",
    distanceFromNairobi: "2 hrs drive",
  },
  {
    id: "hike-007",
    title: "Castle Forest Waterfalls Trek",
    description:
      "Discover hidden waterfalls, indigenous forests, and crystal-clear streams on this scenic Mount Kenya forest adventure.",
    image: "/explore/castle.png",
    difficulty: "Intermediate",
    duration: "2 Days",
    price: 9800,
    rating: 4.7,
    location: "Kirinyaga County",
    distanceFromNairobi: "3 hrs drive",
  },
  {
    id: "hike-008",
    title: "Menengai Crater Rim Hike",
    description:
      "Explore one of Africa's largest volcanic calderas while enjoying sweeping views of Nakuru and the Great Rift Valley.",
    image: "/explore/menengai-2.png",
    difficulty: "Beginner",
    duration: "1 Day",
    price: 3000,
    rating: 4.6,
    location: "Nakuru County",
    distanceFromNairobi: "3 hrs drive",
  },
];
